kumuluzee:
  name: dostavca-packet
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: localhost:8081
    http:
      port: 8081
  discovery:
    cluster: dostavca
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
